#!/bin/bash

. /opt/setup_lib.sh

user=forum.hippy.ru
forum_website=www.hippy.ru/forum

log "Generating PHP config for $forum_website"

forum_cache="$(get_scratch_dir $user)/forum-cache/"
mkdir -p "$forum_cache"
chmod 770 "$forum_cache"

# Hack to workaround fluxbb limitation that requires the upload dir to reside
# under the tree with php sources.

rm -rf /www/soft/fluxbb/img/avatars
ln -s /www/site/forum.hippy.ru/html/img/avatars /www/soft/fluxbb/img/avatars

load_php_db_info $user

write_php_auto_prepend $user <<EOF
<?php
\$db_host     = ':$mysql_socket';
\$db_username = '$php_db_user';
\$db_password = '$php_db_password';
\$db_name     = '$php_db_name';

\$db_type = 'mysql';
\$db_prefix = 'f_';
\$p_connect = false;

\$base_url = 'https://$forum_website';

\$cookie_name = 'punbb_cookie';
\$cookie_domain = '';
\$cookie_path = '/';
\$cookie_secure = 0;

define('FORUM', 1);
define('FORUM_DISABLE_CSRF_CONFIRM', 1);

define('FORUM_CACHE_DIR', '$forum_cache');
EOF
